
#pragma once
#define EXAMPLE_LCD_H_RES 376
#define EXAMPLE_LCD_V_RES 960

#if CONFIG_EXAMPLE_DOUBLE_FB
#define EXAMPLE_LCD_NUM_FB 2
#else
#define EXAMPLE_LCD_NUM_FB 1
#endif // CONFIG_EXAMPLE_DOUBLE_FB

#define EXAMPLE_LCD_PIXEL_CLOCK_HZ (16 * 1000 * 1000)
#define EXAMPLE_LCD_BK_LIGHT_ON_LEVEL 1
#define EXAMPLE_LCD_BK_LIGHT_OFF_LEVEL !EXAMPLE_LCD_BK_LIGHT_ON_LEVEL
#define EXAMPLE_PIN_NUM_BK_LIGHT GPIO_NUM_4
#define EXAMPLE_PIN_NUM_HSYNC 6
#define EXAMPLE_PIN_NUM_VSYNC 5
#define EXAMPLE_PIN_NUM_DE 15
#define EXAMPLE_PIN_NUM_PCLK 7

#define EXAMPLE_PIN_NUM_DATA0 47 // B0
#define EXAMPLE_PIN_NUM_DATA1 21 // B1
#define EXAMPLE_PIN_NUM_DATA2 14 // B2
#define EXAMPLE_PIN_NUM_DATA3 13 // B3
#define EXAMPLE_PIN_NUM_DATA4 12 // B4

#define EXAMPLE_PIN_NUM_DATA5 11  // G0
#define EXAMPLE_PIN_NUM_DATA6 10  // G1
#define EXAMPLE_PIN_NUM_DATA7 9   // G2
#define EXAMPLE_PIN_NUM_DATA8 46  // G3
#define EXAMPLE_PIN_NUM_DATA9 3   // G4
#define EXAMPLE_PIN_NUM_DATA10 20 // G5

#define EXAMPLE_PIN_NUM_DATA11 19 // R0
#define EXAMPLE_PIN_NUM_DATA12 8  // R1
#define EXAMPLE_PIN_NUM_DATA13 18 // R2
#define EXAMPLE_PIN_NUM_DATA14 17 // R3
#define EXAMPLE_PIN_NUM_DATA15 16 // R4

#define EXAMPLE_PIN_NUM_DISP_EN -1

#define TEST_LCD_IO_SPI_CS_1 (GPIO_NUM_48)
#define TEST_LCD_IO_SPI_SCL_1 (GPIO_NUM_17)
#define TEST_LCD_IO_SPI_SDO_1 (GPIO_NUM_16)